# Generated by Django 4.2 on 2024-09-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipoEntrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoentrada',
            name='nombre',
            field=models.CharField(choices=[('compras', 'Compras'), ('devolucion', 'Devolución')], max_length=100, verbose_name='Nombres'),
        ),
    ]
