# Generated by Django 4.2 on 2024-09-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoEntrada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.CharField(max_length=100, verbose_name='FechaEntrada')),
                ('tipoentrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TipoEntrada.tipoentrada', verbose_name='TipoEntrada')),
            ],
            options={
                'verbose_name': 'TiposEntradas',
            },
        ),
    ]
