# Generated by Django 4.2 on 2024-09-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='fechaEntrada',
            new_name='fechaentrada',
        ),
    ]
