# Generated by Django 4.2 on 2024-09-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='existencia',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Existencia'),
        ),
    ]
