# Generated by Django 4.2 on 2024-09-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrada', '0001_initial'),
        ('Libros', '0002_alter_libro_existencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoactual', models.BigIntegerField(blank=True, null=True, verbose_name='CostoActual')),
                ('cantidad', models.BigIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Entrada.entrada', verbose_name='Entrada')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libros.libro', verbose_name='Libro')),
            ],
        ),
    ]
